(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-file-name-transforms '((".*" "~/.cache/emacs-backups/" t)))
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.cache/emacs-backups")))
 '(cider-repl-display-help-banner nil t)
 '(cider-repl-tab-command nil t)
 '(company-backends '(company-capf company-files))
 '(company-frontends
   '(company-pseudo-tooltip-unless-just-one-frontend company-preview-frontend company-echo-metadata-frontend))
 '(company-idle-delay 0.0)
 '(company-minimum-prefix-length 2)
 '(company-posframe-quickhelp-show-header nil)
 '(company-posframe-quickhelp-show-params
   '(:poshandler company-posframe-quickhelp-right-poshandler :internal-border-width 1 :timeout 60 :internal-border-color "#1d2026" :no-properties nil :poshandler nil) t)
 '(company-posframe-show-indicator nil)
 '(company-posframe-show-metadata nil)
 '(company-require-match 'never)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-maximum-width 60)
 '(company-tooltip-minimum-width 30)
 '(create-lockfiles nil)
 '(css-indent-offset 2)
 '(custom-file "/home/riccardo/.emacs.d/custom.el")
 '(default-input-method 'russian-computer)
 '(display-line-numbers-grow-only t)
 '(display-line-numbers-width-start t)
 '(doc-view-resolution 192)
 '(doom-modeline-bar-width 3)
 '(doom-modeline-buffer-color-icon nil t)
 '(doom-modeline-buffer-file-name-style 'relative-from-project)
 '(doom-modeline-height 32)
 '(doom-modeline-major-mode-color-icon nil)
 '(doom-modeline-minor-modes t)
 '(doom-themes-enable-bold t)
 '(doom-themes-enable-italic t)
 '(ediff-split-window-function 'split-window-horizontally t)
 '(enable-recursive-minibuffers t)
 '(find-file-visit-truename t)
 '(flymake-fringe-indicator-position 'right-fringe)
 '(geiser-active-implementations '(guile))
 '(geiser-default-implementation 'guile)
 '(help-window-select t)
 '(iedit-toggle-key-default nil t)
 '(inhibit-splash-screen t)
 '(inhibit-startup-screen t)
 '(initial-major-mode 'fundamental-mode)
 '(initial-scratch-message "")
 '(ivy-count-format "")
 '(ivy-display-style nil)
 '(ivy-ignore-buffers '("\\` " "\\`\\*"))
 '(ivy-minibuffer-faces '(default default default default))
 '(ivy-posframe-display-functions-alist '((t . aorst/posframe-position)))
 '(ivy-posframe-height-alist '((t . 16)))
 '(ivy-posframe-parameters '((internal-border-width . 6)))
 '(ivy-posframe-width 78)
 '(ivy-re-builders-alist '((t . ivy--regex-fuzzy)) t)
 '(ivy-use-virtual-buffers t)
 '(lsp-enable-symbol-highlighting nil)
 '(lsp-keymap-prefix "C-c l")
 '(lsp-prefer-capf t)
 '(lsp-rust-clippy-preference "on")
 '(lsp-rust-server 'rust-analyzer)
 '(lsp-ui-doc-border "#1d2026")
 '(lsp-ui-doc-delay 0.7)
 '(lsp-ui-imenu-enable nil)
 '(lsp-ui-sideline-enable nil)
 '(magit-ediff-dwim-show-on-hunks t t)
 '(nrepl-hide-special-buffers t t)
 '(org-adapt-indentation nil)
 '(org-agenda-files '("~/Tasks"))
 '(org-confirm-babel-evaluate nil)
 '(org-hide-emphasis-markers t)
 '(org-hide-leading-stars t)
 '(org-highlight-latex-and-related '(latex))
 '(org-imenu-depth 8)
 '(org-latex-listings 'minted)
 '(org-latex-pdf-process
   '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
 '(org-log-done t)
 '(org-preview-latex-default-process 'dvisvgm)
 '(org-preview-latex-image-directory ".ltximg/")
 '(org-src-fontify-natively t)
 '(org-startup-folded 'content)
 '(org-startup-with-inline-images nil)
 '(org-tags-column -100)
 '(package-last-refresh-date "2020-05-15T12:34")
 '(package-selected-packages
   '(pyvenv ess lsp-python-ms which-key dap-PYTHON dap-python dap-mode lsp-treemacs lsp-ivy evil multi-term treemacs-magit separedit edit-indirect clang-format lsp-ui lsp-mode iedit expand-region mc-extras multiple-cursors magit yasnippet undo-tree company-posframe company ivy-posframe counsel ivy flx selected paredit geiser editorconfig vterm lua-mode fennel-mode cider clojure-mode yaml-mode cmake-mode racket-mode toml-mode rust-mode markdown-mode ox-hugo minions treemacs doom-modeline solaire-mode doom-themes all-the-icons use-package))
 '(parinfer-extensions '(defaults pretty-parens smart-tab smart-yank) t)
 '(revert-without-query '(".*.pdf"))
 '(separedit-default-mode 'markdown-mode t)
 '(solaire-mode-real-buffer-fn 'aorst/real-buffer-p)
 '(treemacs-indentation 2)
 '(treemacs-is-never-other-window t)
 '(treemacs-space-between-root-nodes nil)
 '(treemacs-width 34)
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(user-full-name "Andrey Orst")
 '(user-mail-address "andreyorst@gmail.com")
 '(window-divider-default-right-width 1))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cider-deprecated-face ((t (:inherit smerge-upper))))
 '(cider-error-highlight-face ((t (:inherit flymake-error))))
 '(cider-fragile-button-face ((t (:box (:line-width -1 :color nil :style nil) :inherit (font-lock-warning-face)))))
 '(cider-fringe-face ((t (:inherit flymake-warning))))
 '(cider-instrumented-face ((t (:box (:line-width -1 :color "#ff6c6b" :style nil)))))
 '(parinfer--error-face ((t (:inherit (flymake-error))))))
